### PR TITLE
UI: Update dynamic header font-size

### PR DESCRIPTION
**Pull request by drewsamsen**
#### New Changes
- Instead of changing header font size by word count at specific thresholds, updates based on each character and uses exponential backoff function
#### Notes

Please PR against the staging branch

### CODE REVIEW

**Comment by taylorpoe** [comment]
Nice! This function went from _gross_ to fireworks.

**Comment by drewsamsen** [comment]
I hope the constant font-size changing isn't disorienting though...

**Comment by taylorpoe** [comment]
I was wondering that too, but hands on ux was way better for me than it was — no more jarring 10px font-size jumps. Really fluid now. Have you ever seen this sort of thing anywhere before? I think it's kind of nice and haven't seen it before.

**Comment by drewsamsen** [comment]
No haven't seen it before, though it might be smooth though 👍

**Pull request merged**
